---
output: github_document
title: "Net Electricity Consumption"
---

Visualization of electricity produced by balcony power station and net electricity usage measured by electricity meter.

<div>
by <a href="mailto:firstname.lastname@outlook.com">Konstantin</a> on `r Sys.Date()`
</div>

```{r init, echo = FALSE}
# load packages
library(conflicted)
library(dplyr)
library(forcats)
library(ggplot2)
library(knitr)
library(readxl)
library(purrr)
library(stringr)
library(tibble)
library(tidyr)

# solve package conflicts
# conflict_scout()
conflicts_prefer(dplyr::filter(), dplyr::lag(), .quiet = TRUE)

# set knitr options
opts_chunk$set(echo = FALSE, fig.path = file.path("img", ""))
```

```{r data-prep}
source(file.path("scripts", "data_prep.R"))
```

<!-- Start of analysis -------------------------------------------------------->

```{r average-net-usage}
df_em %>% 
  ggplot(mapping = aes(x = dt, y = avgu)) +
  geom_hline(yintercept = 0, color = gray(.5)) + 
  geom_vline(
    xintercept = as.Date(paste0(2023:2026, "-01-01")),
    color = gray(.5), linetype = "dashed"
  ) + 
  geom_vline(xintercept = as.Date("2025-07-07"), color = "red") + 
  annotate(
    geom = "text", x = as.Date("2025-07-07"), y = 0,
    label = "1st day of power station",
    angle = 90, hjust = -.1, vjust = -.5, color = "red"
  ) + 
  geom_point() + 
  geom_step(direction = "vh") + 
  labs(
    x = NULL, y = "kWh", fill = NULL,
    title = "Daily average net electricity usage"
  ) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y", minor_breaks = NULL) + 
  scale_y_continuous(breaks = 0:9, minor_breaks = NULL, expand = expansion(mult = c(0, .05))) + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 0, vjust = .5))
```

```{r prod-daily}
avg_usage <- df_em %>% 
  filter(dt %in% c(as.Date(c("2023-12-31", "2024-12-31")))) %>% pull(kwh) %>%
  diff() %>% {./365}

df_ps_daily %>% 
  ggplot(mapping = aes(x = dt, y = prod)) +
  facet_grid(cols = vars(month), scales = "free_x", space = "free_x") + 
  geom_hline(yintercept = avg_usage) + 
  geom_col() + 
  geom_text(
    aes(label = sprintf(fmt = "%.1f", prod)),
    position = position_stack(vjust = 0.5),
    size = 3, color = "white", angle = 90
  ) +
  scale_x_date(
    date_breaks = "1 week", date_labels = "%d %b", minor_breaks = NULL
  ) +
  scale_y_continuous(
    breaks = 0:9, minor_breaks = NULL,
    expand = expansion(mult = c(0, .05)),
    sec.axis = dup_axis(breaks = round(avg_usage, digits = 2), name = NULL)
  ) + 
  labs(
    x = NULL, y = "kWh", fill = NULL,
    title = "Power station production"
  ) + 
  theme_minimal() + 
  theme(legend.position = "bottom")
```

```{r prod-details}
auc <- \(x, y) {
  #-- df <- df_ps_detail_auc$data[[1]]
  #-- x <- df$tm; y <- df$value
  n <- length(x)
  a <- 0.5 * (y[1:(n-1)] + y[2:n]) * (x[2:n] - x[1:(n-1)])
  sum(as.numeric(a))
}

df_ps_detail_auc <- 
  df_ps_detail_sum %>% 
  nest(data = -name) %>% 
  mutate(auc = map_dbl(data, .f = ~auc(.x$tm, .x$value))) %>% 
  select(-data)
  
df_ps_detail_sum %>%
  left_join(y = df_ps_detail_auc, by = join_by(name)) %>% 
  mutate(aux = paste0(name, ": ", sprintf(fmt = "%.2f kWh", auc/1000)) %>% fct_inorder()) %>% 
  ggplot(mapping = aes(x = tm, y = value, group = aux, color = aux)) + 
  geom_hline(yintercept = 0, color = gray(.5)) + 
  geom_line() + 
  scale_x_continuous(breaks = 0:24, minor_breaks = NULL) + 
  scale_y_continuous(expand = expansion(mult = c(0, .05))) + 
  labs(
    x = "Hour",
    y = "Watt",
    color = NULL,
    title = "Quartiles of power station production",
  ) + 
  theme_minimal()
```



<!-- End of analysis ---------------------------------------------------------->
